- make debtransfrom configurable via the dsc file - print error and abort if debtransform fails - add new setdeps function to Build.pm - support macros in config files - remove cp call from init_buildsystem (cp may depend on libacl)

diff --git a/build b/build
--- a/build
+++ b/build
@@ -725,7 +725,10 @@ for SPECFILE in $SPECFILES ; do
 	if test -n "$DEB_TRANSFORM" ; then
 	    echo "running debian transformer..."
 	    mkdir -p $BUILD_ROOT$TOPDIR/SOURCES.DEB
-            debtransform $CHANGELOGARGS $BUILD_ROOT$TOPDIR/SOURCES $BUILD_ROOT$TOPDIR/SOURCES/$SPECFILE $BUILD_ROOT$TOPDIR/SOURCES.DEB
+            if ! debtransform $CHANGELOGARGS $BUILD_ROOT$TOPDIR/SOURCES $BUILD_ROOT$TOPDIR/SOURCES/$SPECFILE $BUILD_ROOT$TOPDIR/SOURCES.DEB ; then
+		echo "debian transforming failed."
+		cleanup_and_exit 1
+	    fi
 	    chroot $BUILD_ROOT su -c "dpkg-source -x $TOPDIR/SOURCES.DEB/*.dsc $TOPDIR/BUILD" - $BUILD_USER
         else
 	    chroot $BUILD_ROOT su -c "dpkg-source -x $TOPDIR/SOURCES/$SPECFILE $TOPDIR/BUILD" - $BUILD_USER
