build-recipe-simpleimage build-recipe-preinstallimage init_buildsystem : a bit more verbosity about I/O-heavy operations, to help profile them better

diff --git a/build-recipe-simpleimage b/build-recipe-simpleimage
--- a/build-recipe-simpleimage
+++ b/build-recipe-simpleimage
@@ -19,7 +19,7 @@ recipe_prepare_simpleimage() {
 recipe_build_simpleimage() {
     TOPDIR=/usr/src/packages
 
-    echo "creating simple image..."
+    echo "`date -u`: creating simple image..."
     cd $BUILD_ROOT || cleanup_and_exit 1
     export SRCDIR="$TOPDIR/SOURCES"
 
@@ -31,12 +31,12 @@ recipe_build_simpleimage() {
     SHELL="/bin/sh"
     [ -x $BUILD_ROOT/bin/bash ] && SHELL="/bin/bash"
     if [ "`grep '^%build$' $BUILD_ROOT$TOPDIR/SOURCES/simpleimage`" ]; then
-      echo "Running integration script..."
+      echo "`date -u`: Running integration script..."
       sed -n '/%build/,$ p' $BUILD_ROOT$TOPDIR/SOURCES/simpleimage | tail -n +2 | chroot $BUILD_ROOT $SHELL -x || cleanup_and_exit 1
-      echo "Integration script finished."
+      echo "`date -u`: Integration script finished."
     fi
 
-    echo "Finalizing filesystem tree..."
+    echo "`date -u`: Finalizing filesystem tree..."
     TOPDIRS=
     for DIR  in .* * ; do
       case "$DIR" in
@@ -57,9 +57,9 @@ recipe_build_simpleimage() {
     mkdir -p .tmp/{proc,sys}
 
     if [ -n "$REMOTE_IO_EXEC" ]; then
-        echo "Compresing the final image using REMOTE_IO_EXEC, this can take a while..."
+        echo "`date -u`: Compresing the final image using REMOTE_IO_EXEC, this can take a while..."
     else
-        echo "Compresing the final image, this can take a while..."
+        echo "`date -u`: Compresing the final image, this can take a while..."
     fi
     echo
 
@@ -92,19 +92,32 @@ recipe_build_simpleimage() {
       # Note: no pigz magic here, mksquashfs already does parallel work by itself
       REMOTE_IO_EXEC mksquashfs $TOPDIRS .tmp/proc .tmp/sys $BUILD_ROOT/.simpleimage.squashfs -info -keep-as-directory -no-progress || cleanup_and_exit 1
     fi
-    echo "simple image created."
+    echo "`date -u`: simple image created."
 
     DEST="$BUILD_ROOT$TOPDIR/OTHER"
     mkdir -p "$DEST"
+
+    echo
+    echo "Checksumming tarball..."
+    echo
     mv $BUILD_ROOT/.simpleimage.tar.gz $DEST/$NAME-${VERSION}_${BUILD_ARCH%%:*}.tar.gz
     REMOTE_IO_EXEC md5sum $DEST/$NAME-${VERSION}_${BUILD_ARCH%%:*}.tar.gz | sed "s|$DEST/||" > $DEST/$NAME-${VERSION}_${BUILD_ARCH%%:*}.tar.gz.md5
+    ls -la $DEST/$NAME-${VERSION}_${BUILD_ARCH%%:*}.tar.gz.md5 $DEST/$NAME-${VERSION}_${BUILD_ARCH%%:*}.tar.gz
+
     if [ -r .simpleimage.squashfs ]; then
+      echo
+      echo "Checksumming squashfs..."
+      echo
       mv $BUILD_ROOT/.simpleimage.squashfs $DEST/$NAME-${VERSION}_${BUILD_ARCH%%:*}.squashfs
       REMOTE_IO_EXEC md5sum $DEST/$NAME-${VERSION}_${BUILD_ARCH%%:*}.squashfs | sed "s|$DEST/||" > $DEST/$NAME-${VERSION}_${BUILD_ARCH%%:*}.squashfs.md5
+      ls -la $DEST/$NAME-${VERSION}_${BUILD_ARCH%%:*}.squashfs.md5 $DEST/$NAME-${VERSION}_${BUILD_ARCH%%:*}.squashfs
     fi
+
+    echo "Almost done, cleaning up..."
     rm -f $BUILD_ROOT/.build.packages
     ln -s ${TOPDIR#/} $BUILD_ROOT/.build.packages
-    test -d "$SRCDIR" && cd "$SRCDIR"
+    echo "`date -u`: recipe_build_simpleimage() finished"
+    test -d "$SRCDIR" && cd "$SRCDIR" || echo "NOTE: Could not test existance of SRCDIR='$SRCDIR'"
     cleanup_and_exit 0
 }
 
