- do not fail with fallocate on old filesystems

diff --git a/build-vm b/build-vm
--- a/build-vm
+++ b/build-vm
@@ -322,8 +322,15 @@ vm_img_create() {
     echo "$size" > "${img}.size"
     # allocate blocks
     if type -p fallocate > /dev/null ; then
-        fallocate -p -l "${size}M" "$img"
-        fallocate -l "${size}M" "$img" || cleanup_and_exit 3
+        fallocate -p -l "${size}M" "$img" 2> /dev/null
+        errout=$( fallocate -l "${size}M" "$img" 2>&1 )
+        if test $? != 0; then
+            echo $errout
+            if test "${errout/Operation not supported/}" = "$errout"; then
+                # Do not fail on not support file systems, eg ext2 or ext3
+                cleanup_and_exit 3
+            fi
+        fi
     fi
 }
 
