Rework label setting for the root filesystem
Now with a flexible label!

diff --git a/build-vm b/build-vm
--- a/build-vm
+++ b/build-vm
@@ -24,11 +24,11 @@
 # defaults for vm_img_mkfs
 vm_img_mkfs_ext4_options='-O ^has_journal,^huge_file,^resize_inode,sparse_super'
 vm_img_mkfs_ext4_extra='-E lazy_itable_init,discard'
-vm_img_mkfs_ext4="mkfs.ext4 -L obsrootfs -m 0 -q -F $vm_img_mkfs_ext4_options"
+vm_img_mkfs_ext4="mkfs.ext4 -m 0 -q -F $vm_img_mkfs_ext4_options"
 vm_img_tunefs_ext4='tune2fs -c 0'
-vm_img_mkfs_ext3='mkfs.ext3 -L obsrootfs -m 0 -q -F'
+vm_img_mkfs_ext3='mkfs.ext3 -m 0 -q -F'
 vm_img_tunefs_ext3='tune2fs -c 0 -o journal_data_writeback'
-vm_img_mkfs_ext2='mkfs.ext2 -L obsrootfs -m 0 -q -F'
+vm_img_mkfs_ext2='mkfs.ext2 -m 0 -q -F'
 vm_img_tunefs_ext2='tune2fs -c 0'
 vm_img_mkfs_reiserfs='mkreiserfs -q -f'
 vm_img_mkfs_btrfs='mkfs.btrfs'
@@ -366,6 +366,8 @@ vm_img_mkfs() {
     eval "mkfs=\"\$vm_img_mkfs_${fs}\""
     eval "mkfs_exta_options=\"\$vm_img_mkfs_${fs}_extra\""
     eval "tunefs=\"\$vm_img_tunefs_${fs}\""
+    local labelopt=
+    test "$VM_ROOTDEV" != "${VM_ROOTDEV#LABEL=}" && labelopt="-L ${VM_ROOTDEV#LABEL=}"
 
     if test -z "$mkfs"; then
 	cleanup_and_exit 3 "filesystem \"$fs\" is not supported"
@@ -373,12 +375,12 @@ vm_img_mkfs() {
 
     echo "Creating $fs filesystem on $img"
     export MKE2FS_SYNC=0
-    if ! $mkfs $mkfs_exta_options "$img"; then
-        if test -z "$mkfs_exta_options"; then
+    if ! $mkfs $labelopt $mkfs_exta_options "$img" ; then
+        if test -z "$mkfs_exta_options" ; then
             cleanup_and_exit 3
         else
-            echo "Format call failed, trying again without extra options..."
-            $mkfs "$img" || cleanup_and_exit 3
+            echo "Filesystem creation failed, trying again without extra options..."
+            $mkfs $labelopt "$img" || cleanup_and_exit 3
         fi
     fi
     if test -n "$tunefs" ; then
