Return correct exit code from lxc build.
In lxc version 3, lxc-start returns zero exit code,
even if a command started in the container returned non-zero exit code.
Fortunately, we still can retrieve exit code of build
from "$BUILD_ROOT/.build/_exitcode" file.

Signed-off-by: Oleg Girko <ol@infoserver.lv>

diff --git a/build-vm-lxc b/build-vm-lxc
--- a/build-vm-lxc
+++ b/build-vm-lxc
@@ -93,6 +93,12 @@ vm_startup_lxc_standalone() {
            cleanup_and_exit 1
            ;;
     esac
+    if ! [ -r "$BUILD_ROOT/.build/_exitcode" ]; then
+        echo "'$BUILD_ROOT/.build/_exitcode' not found"
+        return 3
+    fi
+    exitcode=$(cat $BUILD_ROOT/.build/_exitcode)
+    return "$exitcode"
 }
 
 vm_startup_lxc_libvirt() {
